#!/usr/bin/perl
# SPDX-License-Identifier: MIT

use strict;
use warnings;
use utf8;
binmode(STDOUT, ":utf8");

sub head {
printf "U+nnnn | ";
for (my $x = 0; $x < 64; $x += 4) {
	if ($x % 16 == 0) {
		printf "%x   ", int($x / 16);
	} else {
		print "    ";
	}
}
print "\n";
printf "U+nnnn | ";
for (my $x = 0; $x < 64; ++$x) {
	printf "%x", $x % 16;
}
print "\n";
print "-" x 74;
print "\n";
}

&head();
for (my $y = 64; $y < 0x2c00; $y += 64) {
	if ($y % 0x400 == 0) {
		printf("\n");
		&head();
	}
	printf "U+%04x | ", $y;
	for (my $x = 0; $x < 64; ++$x) {
		print chr($y+$x);
	}
	print "\n";
}
