.TH clt2bdf 1 "2014-01-09" "hxtools" "hxtools"
.SH Name
.PP
clt2bdf \(em convert Consoleet text bitmaps to Glyph Bitmap Distribution Format
.SH Syntax
\fBclt2bdf\fP \fB\-o\fP \fIoutput.bdf\fP \fIdirectory\fP...
.SH Description
clt2bdf scans one or more directories recursively for Consoleet text bitmap
files, collects and converts these into a single BDF file. The names of the
bitmap files have to match the Unicode point the glyph is representing.

