.TH clt2bdf 1 "2014-01-09" "hxtools" "hxtools"
.SH Name
.PP
clt2bdf \(em convert Consoleet text bitmaps to BDF/SFD
.SH Syntax
\fBclt2bdf\fP [\fB\-\-bdf\fP|\fB\-\-sfd\fP] [\fB\-O\fP]
[\fB\-N\fP \fIname\fP] \fB\-o\fP \fIoutput.bdf\fP \fIdirectory\fP...
.SH Description
.PP
clt2bdf scans one or more directories recursively for Consoleet text bitmap
files, collects and converts these into a single BDF or SFD file. The names of
the bitmap files have to match the Unicode point the glyph is representing.
The default output format is SFD.
.PP
In case of SFD generation, each pixel is transformed into a polygon. This means
the file will be bloated, and you are encouraged to run the FontForge editing
tools to combine polygons, either via UI or the command line,
.PP
fontforge -lang=ff 'Open("foo.sfd"); SelectAll(); RemoveOverlap(); Simplify(-1,
1; Save("foo.sfd");'
.SH Options
.TP
\fB\-N\fP
Display name for the new font.
.TP
\fB\-O\fP
Feed the SFD data output by clt2bdf through FontForge for merging of
overlapping polygons and vertices.
.TP
\fB\-\-bdf\fP
Generate a Glyph Bitmap Distribution file, which can then be edited further
with gbdfed. Use this if you plan on generating a PCF (with bdftopcf) for use
with the X server.
.TP
\fB\-\-sfd\fP
Generate a Spline Font Database file, which can then be edited further with
FontForge and converted to TrueType/OpenType.
.TP
\fB\-o\fP \fIfile\fP
Specify the name of the output file.
