.TH palcomp 1 "2022-10-23" "hxtools" "hxtools"
.SH Name
palcomp \(em palette composer
.SH Syntax
\fBpalcomp\fP [commands...]
.SH Description
palcomp can be used to generate palettes for terminals. The most important
realization is that programs running within a terminal and which use
console_codes(4) to set colors rely on the \fBcontrast\fP of the colors
produced by a color pairing to be proportional to the contrast those two codes
have when using the VGA color palette. For this reason, a mainstay of this
program is to operate using a colorspace with perceptual uniformity, i.e.
CIELAB/LCh.
.SH Commands
.SS bg
Emit a -bg parameter upon xterm, and use color 0.
.SS debug
Turn on individual colorspace conversion reporting.
.SS emit
Emit the the RGB palette as a line for an XDG theme file.
.SS fg
Emit a -fg parameter upon xterm, and use color 7.
.SS hueadd=h
Add an offset (0 <= h < 360) to the LCh palette's h values.
.SS hueset=h
Set the LCh palette's h values to a fixed value (0 <= h < 360).
.SS lch
Computes the LCh-based palette from the current in-memory RGB palette, and
stores the result in the LCH slot.
.SS litadd=r
Add an offset to the LCh palette's L values.
.SS litmul=r
Multiply the h values in the LCh palette by r.
.SS litset=r
Set the LCh palette's L values to a fixed value.
.SS rgb
Computes the RGB-based palette from the current in-memory LCh palette, and
stores the result in the RGB slot.
.SS satadd=r
Add an offset to the LCh palette's C values.
.SS satmul=r
Multiplies the C channel of the LCH palette's colors with factor \fIr\fP. In
effect, with r<1, this causes a desaturation of colors; r=0 leads to gray.
.SS satset=r
Set the LCh palette's C values to a fixed value.
.SS hsltint=h,s,l
Map the LCh palette brightnesses onto a color line through the HSL cylinder
that goes from black to the chosen color. Parameter ranges are (0 <= h < 360; 0
<= s < 1; 0 <= l <= 1). The result of the operation is stored in the RGB
palette. When using s<=0.5, this produces a black-to-{color} ramp; when using
s==1, this produces a black-to-{color}-to-white ramp.
.PP
hsltint produces a somewhat more contrasty result than manipulating hue and
saturation in LCh. Compare:
.IP \(bu 4
palcomp vgs lch satset=100 hueset=120 rgb emit
.IP \(bu 4
palcomp vgs lch hsltint=90,1,0.5 emit
.SS hsltint=#rrggbb[,l]
A different syntax for the hsltint operation. First, the RGB value for the tint
color is converted to HSL. The so-computed L value can be overridden with the
optional \fB,\fP\fIl\fP suffix. Afterwards, behaves like hsltint=h,s,l.
.SS vga
Loads the standard VGA palette into the RGB slot.
.SS vgs
Loads a full-saturated VGA palette into the RGB slot.
.SS xterm
Emit the RGB palette as xterm command line options. Use e.g. `xterm $(palcomp
vga lch hueset=120 rgb xterm)` to utilize.
.SH Examples
.PP
Black-to-green ramp (tint via HSL color space):
.IP \(bu 4
palcomp vgs lch hsltint=120,1,0.5 emit
.IP \(bu 4
palcomp vgs lch hsltint=#00ff00 emit
.PP
Black-to-green-white ramp (tint via HSL color space):
.IP \(bu 4
palcomp vgs lch hsltint=120,1,1 emit
.IP \(bu 4
palcomp vgs lch hsltint=#00ff00,1 emit
.SH See also
\fBhxtools\fP(7)
